spring:
  datasource:
    url: jdbc:mysql://localhost:3306/yeongkkeul?useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: root
    password: kmh990104
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: never
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
        hbm2ddl:
          auto: create
        default_batch_fetch_size: 1000
external:
  jwt:
    secret: ${JWT_SECRET_KEY:9aa2cf78df2db0445735e0bea567dba2d7a34faa668837d887bbcc8b45a125426c96e179685f61ce890c1d0a8f76234547ab6419c4c5e688203dedfff3436b56}

