spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: never
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
        hbm2ddl:
          auto: update
        default_batch_fetch_size: 1000
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 300MB

external:
  jwt:
    secret: ${JWT_SECRET_KEY}

kakao:
  redirect-url: https://localhost:8080/login/oauth2/callback/kakao
  client-id: ${KAKAO_CLEINT_ID}
  client-secret: ${KAKAO_CLIENT_SECRET}
